spring.application.name=ls06_ForumService
server.error.include-message=always
spring.data.mongodb.uri=mongodb+srv://kslemming511:19525Qi45@cluster0.uejrsvm.mongodb.net/forum?retryWrites=true&w=majority